#!/bin/bash
# release.sh — bump plugin version, tag, push, and create a GitHub Release.
#
# Usage:
#   ./scripts/release.sh <new-version>     # explicit, e.g. 0.2.0
#   ./scripts/release.sh patch             # bump patch (0.1.0 → 0.1.1)
#   ./scripts/release.sh minor             # bump minor (0.1.0 → 0.2.0)
#   ./scripts/release.sh major             # bump major (0.1.0 → 1.0.0)
#
# Runs end-to-end:
#   1. Bumps version in plugins/docks/.claude-plugin/plugin.json AND
#      .claude-plugin/marketplace.json (both must agree per `claude plugin tag`)
#   2. Commits + pushes the version bump
#   3. Runs `claude plugin tag --push` to create + push docks--v<version> tag
#   4. Creates a GitHub Release with autogenerated notes (commits since previous tag)
#
# Preconditions: clean working tree, gh CLI authenticated, jq installed.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PLUGIN_JSON="$REPO_DIR/plugins/docks/.claude-plugin/plugin.json"
MARKETPLACE_JSON="$REPO_DIR/.claude-plugin/marketplace.json"
PLUGIN_PATH="./plugins/docks"

err() { echo "error: $1" >&2; exit 1; }

# --- preconditions ---
command -v jq >/dev/null 2>&1 || err "jq is required"
command -v gh >/dev/null 2>&1 || err "gh is required"
command -v claude >/dev/null 2>&1 || err "claude is required"
[ -f "$PLUGIN_JSON" ] || err "plugin.json not found at $PLUGIN_JSON"
[ -f "$MARKETPLACE_JSON" ] || err "marketplace.json not found at $MARKETPLACE_JSON"

cd "$REPO_DIR"
[ -z "$(git status --porcelain)" ] || err "working tree dirty — commit/stash first"

# --- compute new version ---
ARG="${1:-}"
[ -n "$ARG" ] || err "missing version arg (use X.Y.Z, patch, minor, or major)"

CURRENT=$(jq -r '.version' "$PLUGIN_JSON")
[[ "$CURRENT" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]] || err "current version not semver: $CURRENT"
MAJOR="${BASH_REMATCH[1]}"; MINOR="${BASH_REMATCH[2]}"; PATCH="${BASH_REMATCH[3]}"

case "$ARG" in
  major) NEW_VERSION="$((MAJOR + 1)).0.0" ;;
  minor) NEW_VERSION="$MAJOR.$((MINOR + 1)).0" ;;
  patch) NEW_VERSION="$MAJOR.$MINOR.$((PATCH + 1))" ;;
  *)
    [[ "$ARG" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || err "version must be X.Y.Z, patch, minor, or major (got: $ARG)"
    NEW_VERSION="$ARG"
    ;;
esac

[ "$NEW_VERSION" != "$CURRENT" ] || err "new version equals current ($CURRENT)"

echo "Bumping docks: $CURRENT → $NEW_VERSION"

# --- bump both manifests ---
TMP="$(mktemp)"
jq --arg v "$NEW_VERSION" '.version = $v' "$PLUGIN_JSON" > "$TMP" && mv "$TMP" "$PLUGIN_JSON"
jq --arg v "$NEW_VERSION" '(.plugins[] | select(.name == "docks")).version = $v' "$MARKETPLACE_JSON" > "$TMP" && mv "$TMP" "$MARKETPLACE_JSON"

# --- commit + push the bump ---
git add "$PLUGIN_JSON" "$MARKETPLACE_JSON"
git commit -m "chore(release): docks v$NEW_VERSION"
git push origin HEAD

# --- tag + push ---
claude plugin tag --push --message "docks plugin %s" "$PLUGIN_PATH"

# --- compute release notes from commits since previous tag ---
PREV_TAG=$(git tag --list 'docks--v*' --sort=-version:refname | sed -n '2p')
if [ -n "$PREV_TAG" ]; then
  NOTES=$(git log "$PREV_TAG..HEAD" --pretty=format:'- %s' --no-merges)
  HEADER="Changes since \`$PREV_TAG\`:"
else
  NOTES="Initial release."
  HEADER=""
fi

# --- create GitHub Release ---
gh release create "docks--v$NEW_VERSION" \
  --title "docks v$NEW_VERSION" \
  --notes "$HEADER

$NOTES

## Install

\`\`\`
/plugin marketplace update docks
/plugin install docks@docks
\`\`\`"

echo ""
echo "✔ Released docks v$NEW_VERSION"
echo "  Tag:    docks--v$NEW_VERSION"
echo "  Github: https://github.com/DocksDocks/docks/releases/tag/docks--v$NEW_VERSION"
